Error executing query: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [varchar, varchar, varchar, varchar, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, varchar, varchar, varchar], Query: [varchar(16), varchar(8), varchar(8), varchar(28), varchar(69), varchar(15), varchar(7), varchar(8), varchar, varchar, varchar(8), varchar(8), varchar(134), varchar(255), varchar, varchar, varchar(20), varchar(17), varchar(10), varchar(7), varchar, varchar(14), varchar(16), varchar(15)]", query_id=20250423_065549_43770_uvvzu)
Traceback (most recent call last):
  File "/Users/bhuey/Work/csv2iceberg/trino_client.py", line 150, in execute_query
    cursor.execute(query)
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/dbapi.py", line 614, in execute
    self._iterator = iter(self._query.execute())
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 900, in execute
    self._result.rows += self.fetch()
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 920, in fetch
    status = self._request.process(response)
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 689, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [varchar, varchar, varchar, varchar, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, varchar, varchar, varchar], Query: [varchar(16), varchar(8), varchar(8), varchar(28), varchar(69), varchar(15), varchar(7), varchar(8), varchar, varchar, varchar(8), varchar(8), varchar(134), varchar(255), varchar, varchar, varchar(20), varchar(17), varchar(10), varchar(7), varchar, varchar(14), varchar(16), varchar(15)]", query_id=20250423_065549_43770_uvvzu)
Error in _write_batch_to_iceberg: Failed to execute query: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [varchar, varchar, varchar, varchar, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, varchar, varchar, varchar], Query: [varchar(16), varchar(8), varchar(8), varchar(28), varchar(69), varchar(15), varchar(7), varchar(8), varchar, varchar, varchar(8), varchar(8), varchar(134), varchar(255), varchar, varchar, varchar(20), varchar(17), varchar(10), varchar(7), varchar, varchar(14), varchar(16), varchar(15)]", query_id=20250423_065549_43770_uvvzu)
Traceback (most recent call last):
  File "/Users/bhuey/Work/csv2iceberg/trino_client.py", line 150, in execute_query
    cursor.execute(query)
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/dbapi.py", line 614, in execute
    self._iterator = iter(self._query.execute())
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 900, in execute
    self._result.rows += self.fetch()
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 920, in fetch
    status = self._request.process(response)
  File "/Users/bhuey/Work/csv2iceberg/lib/python3.9/site-packages/trino/client.py", line 689, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=TYPE_MISMATCH, message="Insert query has mismatched column types: Table: [varchar, varchar, varchar, varchar, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, bigint, varchar, varchar, varchar, varchar, bigint, varchar, varchar, varchar], Query: [varchar(16), varchar(8), varchar(8), varchar(28), varchar(69), varchar(15), varchar(7), varchar(8), varchar, varchar, varchar(8), varchar(8), varchar(134), varchar(255), varchar, varchar, varchar(20), varchar(17), varchar(10), varchar(7), varchar, varchar(14), varchar(16), varchar(15)]", query_id=20250423_065549_43770_uvvzu)